/* GENERATED by solve.py — 手で編集しない */
const SUISOU = {
 "themes": [
  {
   "name": "hadal",
   "jp": "超深海層",
   "ladder": "dark",
   "h": 286,
   "cs": 0.006,
   "available": [
    "orange",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "pink"
   ]
  },
  {
   "name": "trench",
   "jp": "海溝",
   "ladder": "dark",
   "h": 265,
   "cs": 0.018,
   "available": [
    "orange",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "pink"
   ]
  },
  {
   "name": "fjord",
   "jp": "峡湾",
   "ladder": "dark",
   "h": 272,
   "cs": 0.03,
   "available": [
    "orange",
    "turtle",
    "teal",
    "coral",
    "magenta",
    "pink"
   ]
  },
  {
   "name": "shoal",
   "jp": "浅瀬",
   "ladder": "dim",
   "h": 265,
   "cs": 0.02,
   "available": [
    "orange",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "pink"
   ]
  }
 ],
 "accents": [
  {
   "name": "orange",
   "jp": "",
   "hue": 55
  },
  {
   "name": "turtle",
   "jp": "ウミガメ",
   "hue": 122
  },
  {
   "name": "teal",
   "jp": "",
   "hue": 188
  },
  {
   "name": "jelly",
   "jp": "クラゲ",
   "hue": 212
  },
  {
   "name": "blue",
   "jp": "",
   "hue": 255
  },
  {
   "name": "indigo",
   "jp": "",
   "hue": 282
  },
  {
   "name": "coral",
   "jp": "サンゴ",
   "hue": 308
  },
  {
   "name": "magenta",
   "jp": "",
   "hue": 332
  },
  {
   "name": "pink",
   "jp": "",
   "hue": 355
  }
 ],
 "themeTokens": [
  "bg",
  "panel",
  "item",
  "floating",
  "hover-surface",
  "line-weak",
  "line-strong",
  "text-disabled",
  "text-sub",
  "text-main",
  "on-accent",
  "scrim",
  "error",
  "warning",
  "success",
  "error-surface",
  "warning-surface",
  "success-surface"
 ],
 "accentTokens": [
  "accent",
  "accent-active",
  "focus-ring",
  "selected-surface"
 ],
 "default": {
  "theme": "hadal",
  "accent": "jelly"
 }
};
