/* GENERATED by solve.py — 手で編集しない */
const SUISOU = {
 "themes": [
  {
   "name": "hadal",
   "jp": "超深海層",
   "ladder": "dark",
   "h": 286,
   "cs": 0.006,
   "available": [
    "clown",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "recommended": [
    "clown",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "warnings": {}
  },
  {
   "name": "trench",
   "jp": "海溝",
   "ladder": "dark",
   "h": 262,
   "cs": 0.044,
   "available": [
    "clown",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "recommended": [
    "clown",
    "turtle",
    "teal",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "warnings": {
    "jelly": "選択下地が面と近い ΔE 0.046（目標 0.055）"
   }
  },
  {
   "name": "fjord",
   "jp": "峡湾",
   "ladder": "dark",
   "h": 278,
   "cs": 0.044,
   "available": [
    "clown",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "recommended": [
    "clown",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "warnings": {}
  },
  {
   "name": "shoal",
   "jp": "浅瀬",
   "ladder": "dim",
   "h": 265,
   "cs": 0.02,
   "available": [
    "clown",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "recommended": [
    "clown",
    "turtle",
    "teal",
    "jelly",
    "blue",
    "indigo",
    "coral",
    "magenta",
    "seal"
   ],
   "warnings": {}
  }
 ],
 "accents": [
  {
   "name": "clown",
   "jp": "カクレクマノミ",
   "hue": 55
  },
  {
   "name": "turtle",
   "jp": "ウミガメ",
   "hue": 122
  },
  {
   "name": "teal",
   "jp": "",
   "hue": 188
  },
  {
   "name": "jelly",
   "jp": "クラゲ",
   "hue": 212
  },
  {
   "name": "blue",
   "jp": "",
   "hue": 255
  },
  {
   "name": "indigo",
   "jp": "",
   "hue": 282
  },
  {
   "name": "coral",
   "jp": "サンゴ",
   "hue": 308
  },
  {
   "name": "magenta",
   "jp": "",
   "hue": 332
  },
  {
   "name": "seal",
   "jp": "アザラシ",
   "hue": 355
  }
 ],
 "themeTokens": [
  "bg",
  "panel",
  "item",
  "overlay",
  "hover-surface",
  "selected-neutral-surface",
  "line-weak",
  "line-weak-panel",
  "line-weak-item",
  "line-weak-overlay",
  "line-weak-hover",
  "line-weak-selected",
  "line-strong",
  "text-disabled",
  "text-sub",
  "text-main",
  "scrim",
  "error",
  "warning",
  "success",
  "error-active",
  "error-surface",
  "warning-surface",
  "success-surface"
 ],
 "accentTokens": [
  "accent",
  "accent-active",
  "focus-ring",
  "selected-surface"
 ],
 "default": {
  "theme": "hadal",
  "accent": "jelly"
 }
};
