#!/usr/bin/env python3
"""公開契約の目録を CSS と solve.py から導く。生成物: CONTRACT.md

「破壊的変更とは何か」を判定するには、まず「何が公開 API か」の一覧が要る。
手で書くとドリフトするので、掟1 と同じ形にする ―― 真実の源泉は
pages/ui/*.css（属性・状態・寸法トークン）と tools/solve.py（色・テーマ・既定）。

使い方:
  python3 tools/contract.py          # CONTRACT.md を書き出す
  python3 tools/contract.py --check  # 照合のみ。ズレていれば exit 1
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, os.pardir))
UI = os.path.join(ROOT, "pages", "ui")

sys.path.insert(0, HERE)
import solve

COMMENT = re.compile(r"/\*.*?\*/", re.S)
ATTR = re.compile(r'\[data-suisou-([a-z-]+)(?:~="([^"]+)")?\]')
STATE = re.compile(r"\[(aria-[a-z-]+|disabled|popover|open)(?:[~^]?=[^\]]*)?\]")
TOKEN_DEF = re.compile(r"(--suisou-[a-z0-9-]+)\s*:")


def ui_files():
    return [os.path.join(UI, n) for n in sorted(os.listdir(UI)) if n.endswith(".css")]


def collect():
    attrs, states = {}, set()
    for p in ui_files():
        css = COMMENT.sub("", open(p, encoding="utf-8").read())
        for name, val in ATTR.findall(css):
            vals = attrs.setdefault(name, [])
            if val:
                base = val.split(":")[-1]          # md: / lg: は同じ値の接頭辞版
                if base not in vals:
                    vals.append(base)
        states |= set(STATE.findall(css))
    # theme / accent は生成物（palette.css）側の属性なので solve から足す
    attrs["theme"] = [t["name"] for t in solve.THEMES]
    attrs["accent"] = [n for n, _ in solve.ACCENTS]
    base = COMMENT.sub("", open(os.path.join(UI, "base.css"), encoding="utf-8").read())
    dims = []
    for name in TOKEN_DEF.findall(base):
        if name not in dims:
            dims.append(name)
    return attrs, sorted(states), dims


def render():
    attrs, states, dims = collect()
    fixed = [n for n, _ in solve.ACCENTS if n in solve.ACCENT_JP]
    provisional = [n for n, _ in solve.ACCENTS if n not in solve.ACCENT_JP]

    L = ["<!-- GENERATED by tools/contract.py — 手で編集しない -->", ""]
    L.append("# Suisou 公開契約")
    L.append("")
    L.append("公開 API の目録。**破壊的変更 ＝ この目録にある名前・値・既定を変える／消すこと**。")
    L.append("足すだけなら非破壊。`/v1/` チャンネルを作るときはこの定義で判定する。")
    L.append("")
    L.append("生成元は `pages/ui/*.css`（属性・状態・寸法）と `tools/solve.py`（色・テーマ・既定）。")
    L.append("`python3 tools/contract.py` で再生成、`--check` で照合。")
    L.append("")

    L.append("## 属性と値")
    L.append("")
    L.append("| 属性 | 値 |")
    L.append("|---|---|")
    for name in sorted(attrs):
        vals = attrs[name]
        L.append(f"| `data-suisou-{name}` | {' '.join(f'`{v}`' for v in vals) if vals else '（値なし）'} |")
    L.append("")
    L.append("- 値は空白区切りで併記できる（`~=` で当たる）")
    L.append("- `layout` の値には `md:` / `lg:` の接頭辞版がある（768px / 1024px、min-width）")
    L.append("- `theme` と `accent` は**必ず同じ要素に書く**（複合選択子でしか定義されない）")
    L.append(f"- `accent` のうち仮名（まだ生き物になっていない）: "
             f"{' '.join(f'`{n}`' for n in provisional)}。確定: {' '.join(f'`{n}`' for n in fixed)}")
    L.append("")

    L.append("## 借りる標準属性（状態）")
    L.append("")
    L.append("自前の data-* を発明せず、これらを見る: " + " ".join(f"`{s}`" for s in states))
    L.append("")

    L.append("## トークン")
    L.append("")
    L.append("色（`palette.css`。値を決めるのは solve.py だけ）:")
    L.append("")
    L.append("- テーマ層: " + " ".join(f"`--suisou-{n}`" for n in solve.THEME_TOKENS))
    L.append("- アクセント層: " + " ".join(f"`--suisou-{n}`" for n in solve.ACCENT_TOKENS))
    L.append("")
    L.append("寸法・書体・モーション（`ui/base.css`）:")
    L.append("")
    L.append("- " + " ".join(f"`{n}`" for n in dims))
    L.append("")

    L.append("## 既定")
    L.append("")
    L.append(f"- 属性が無いとき: `{solve.DEFAULT_THEME}` × `{solve.DEFAULT_ACCENT}`")
    L.append("- layout の子は動かない（`flex: none`）。伸びるものだけ `grow` と名指す")
    L.append("- `button=\"block\"` は左寄せ（全幅のボタンはメニューの行）")
    L.append("")

    L.append("## 配布")
    L.append("")
    L.append("- `dist/suisou.css` … 全部入り（テーマ切替できる）／"
             "`dist/suisou-<theme>-<accent>.css` … 選んだ組だけ")
    L.append("- `/v/<sha7>/…` … 固定 URL。動かない")
    L.append("- **フォントは利用側が読み込む**。既定の書体は Zen Maru Gothic の 400 / 500 / 700")
    L.append("- `helpers.css` は契約外（任意。他にユーティリティが無いときだけ）。"
             "`suisou.data.js` は配布物ではない")
    L.append("")

    L.append("## 明文化した割り切り")
    L.append("")
    L.append("- **accent を文字に使う場所**（outline ボタンのラベル、`tag=\"accent\"`）は "
             "3.0:1 の保証（文字の 4.5 ではない）。意味色の文字は 4.5。"
             "アクセントは常に枠・下線・配置と併用する前提")
    L.append("- **ダーク専用**。純粋なライトは作らない。明るめは `shoal`（dim 階段）")
    L.append("- **JS を要求する部品は作らない**（`<link>` 1本が配布の形）")
    L.append("")
    L.append("<!-- /GENERATED -->")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    out = render()
    path = os.path.join(ROOT, "CONTRACT.md")
    if "--check" in sys.argv:
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if cur != out:
            print("CONTRACT.md が生成元とずれている。python3 tools/contract.py を実行してコミットし直すこと。")
            sys.exit(1)
        print("CONTRACT.md 一致")
        sys.exit(0)
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    print("wrote:", path)
